using PhlanMic.Host.Core;

namespace PhlanMic.WindowsHost;

public sealed record AudioOutputSnapshot(
    string SinkKind,
    int? DeviceId,
    string? DeviceName,
    string? EndpointId,
    string? PairedCaptureEndpointId,
    string? PairedCaptureEndpointName,
    string OutputFormat,
    bool FormatConversionActive,
    int BufferCount,
    int BufferedFrames,
    long SubmittedFrames,
    long CompletedFrames,
    long CompletedBytes,
    long SilenceFramesInserted,
    long UnderrunCount,
    double EstimatedLatencyMs,
    double GlitchRatePerMinute,
    long? LastSequenceNumber,
    DateTimeOffset? StartedAtUtc,
    DateTimeOffset? LastFrameCapturedAtUtc,
    DateTimeOffset? LastSubmittedAtUtc,
    DateTimeOffset? LastCompletedAtUtc,
    AudioLevelMeterSnapshot SignalMeter,
    string? CaptureProbeState,
    string? CaptureProbeFormat,
    long CaptureProbeObservedBytes,
    DateTimeOffset? CaptureProbeLastObservedAtUtc,
    AudioLevelMeterSnapshot CaptureProbeSignalMeter)
{
    public static AudioOutputSnapshot Empty(string sinkKind) => new(
        sinkKind,
        null,
        null,
        null,
        null,
        null,
        "n/a",
        false,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        null,
        null,
        null,
        null,
        null,
        AudioLevelMeterSnapshot.Empty,
        null,
        null,
        0,
        null,
        AudioLevelMeterSnapshot.Empty);
}
