namespace PhlanMic.Host.Core;

public sealed record StreamRobustnessSnapshot(
    StreamRobustnessState State,
    long? ExpectedNextSequence,
    long? HighestReceivedSequence,
    long? HighestBufferedSequence,
    long SequenceGapsObserved,
    long LateFramesArrived,
    long LateFramesDropped,
    long? LastLateRejectedSequence,
    long MissingFramesDetected,
    long SilenceFramesInserted,
    long? LastConcealedSequence,
    int ConsecutiveConcealedFrames,
    long LiveEdgeRecoveryCount,
    long? LastRecoveryPreviousExpectedSequence,
    long? LastRecoveryIncomingSequence,
    int CurrentPrebufferDepth,
    int LargestObservedGap,
    int StartupPrebufferFrames,
    int TargetBufferedFrames,
    int MaxLateFrameToleranceFrames,
    int MissingFrameGraceMs,
    int EstimatedBufferLatencyMs);
